-- Migration: Create platform_announcements table
-- Description: Store platform-wide announcements from admins
-- Author: Generated by Claude Code
-- Date: 2025-12-31

-- Create platform_announcements table
CREATE TABLE IF NOT EXISTS platform_announcements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'info', -- info, warning, success, error
  target_audience TEXT NOT NULL DEFAULT 'all', -- all, users, owners
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_announcements_active ON platform_announcements(is_active, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_announcements_target ON platform_announcements(target_audience);
CREATE INDEX IF NOT EXISTS idx_announcements_expires ON platform_announcements(expires_at);

-- Enable RLS
ALTER TABLE platform_announcements ENABLE ROW LEVEL SECURITY;

-- Policy: Everyone can view active announcements
CREATE POLICY "Anyone can view active announcements"
ON platform_announcements
FOR SELECT
USING (is_active = true);

-- Policy: Admins can insert announcements
CREATE POLICY "Admins can create announcements"
ON platform_announcements
FOR INSERT
WITH CHECK (
  EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid()
    AND (profiles.role IN ('admin', 'super_admin') OR profiles.is_admin = true)
  )
);

-- Policy: Admins can update announcements
CREATE POLICY "Admins can update announcements"
ON platform_announcements
FOR UPDATE
USING (
  EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid()
    AND (profiles.role IN ('admin', 'super_admin') OR profiles.is_admin = true)
  )
);

-- Policy: Admins can delete announcements
CREATE POLICY "Admins can delete announcements"
ON platform_announcements
FOR DELETE
USING (
  EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid()
    AND (profiles.role IN ('admin', 'super_admin') OR profiles.is_admin = true)
  )
);

-- Add comments
COMMENT ON TABLE platform_announcements IS 'Platform-wide announcements from admins to users/owners';
COMMENT ON COLUMN platform_announcements.type IS 'Announcement type: info, warning, success, or error';
COMMENT ON COLUMN platform_announcements.target_audience IS 'Target audience: all, users, or owners';
COMMENT ON COLUMN platform_announcements.expires_at IS 'Optional expiration date for the announcement';
