-- Migration: Ensure cafes table is readable for owner dashboard
-- Description: Add policy to allow reading cafes for owner dashboard
-- Author: Generated by Claude Code
-- Date: 2025-12-31

-- Drop existing policy if it exists
DROP POLICY IF EXISTS "Allow public read access to cafes" ON cafes;

-- Create policy to allow anyone to read cafes
CREATE POLICY "Allow public read access to cafes"
ON cafes
FOR SELECT
USING (true);

-- Add comment
COMMENT ON POLICY "Allow public read access to cafes" ON cafes IS 'Allows anyone to read cafe data including owner dashboard';
