-- Migration: Add featured café functionality
-- Description: Allow admins to feature cafés on the platform
-- Author: Generated by Claude Code
-- Date: 2025-12-31

-- Add is_featured column to cafes table
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'cafes' AND column_name = 'is_featured'
    ) THEN
        ALTER TABLE cafes ADD COLUMN is_featured BOOLEAN NOT NULL DEFAULT false;
    END IF;
END $$;

-- Add featured_order column for controlling display order
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'cafes' AND column_name = 'featured_order'
    ) THEN
        ALTER TABLE cafes ADD COLUMN featured_order INTEGER;
    END IF;
END $$;

-- Add featured_at timestamp
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'cafes' AND column_name = 'featured_at'
    ) THEN
        ALTER TABLE cafes ADD COLUMN featured_at TIMESTAMPTZ;
    END IF;
END $$;

-- Create index for faster featured café queries
CREATE INDEX IF NOT EXISTS idx_cafes_featured ON cafes(is_featured, featured_order);

-- Add comments
COMMENT ON COLUMN cafes.is_featured IS 'Whether the café is featured on the platform';
COMMENT ON COLUMN cafes.featured_order IS 'Display order for featured cafés (lower number = higher priority)';
COMMENT ON COLUMN cafes.featured_at IS 'Timestamp when the café was featured';
