-- Migration: Update existing cafes to have slugs
-- Description: Generate slugs for cafes that don't have one yet
-- Author: Generated by Claude Code
-- Date: 2025-12-20

-- Update cafes without slugs
UPDATE cafes
SET slug = LOWER(
  TRIM(
    BOTH '-' FROM
    REGEXP_REPLACE(
      REGEXP_REPLACE(
        REGEXP_REPLACE(name, '[^a-zA-Z0-9\s-]', '', 'g'),
        '\s+', '-', 'g'
      ),
      '-+', '-', 'g'
    )
  )
)
WHERE slug IS NULL AND name IS NOT NULL;
