-- Migration: Add owner credentials columns
-- Description: Add owner_username and owner_password columns to profiles table for owner login
-- Author: Generated by Claude Code
-- Date: 2025-12-31

-- Add owner_username column
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'profiles' AND column_name = 'owner_username'
    ) THEN
        ALTER TABLE profiles ADD COLUMN owner_username TEXT;
    END IF;
END $$;

-- Add owner_password column (NOTE: In production, use proper password hashing!)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'profiles' AND column_name = 'owner_password'
    ) THEN
        ALTER TABLE profiles ADD COLUMN owner_password TEXT;
    END IF;
END $$;

-- Set default owner credentials for existing owner users
UPDATE profiles
SET
    owner_username = 'owner',
    owner_password = 'owner123'
WHERE
    role = 'owner'
    AND owner_username IS NULL;

-- Add comments
COMMENT ON COLUMN profiles.owner_username IS 'Owner portal login username (only for owner users)';
COMMENT ON COLUMN profiles.owner_password IS 'Owner portal login password - NOTE: Should use proper hashing in production';
