-- Migration: Add customer fields back for walk-in bookings
-- Description: Re-add customer_name and customer_phone for walk-in customers who don't have accounts
-- Author: Generated by Claude Code
-- Date: 2025-12-20

-- Add customer_name and customer_phone columns back
ALTER TABLE bookings
ADD COLUMN IF NOT EXISTS customer_name TEXT,
ADD COLUMN IF NOT EXISTS customer_phone TEXT;

-- Add comment explaining these are for walk-in only
COMMENT ON COLUMN bookings.customer_name IS 'Customer name for walk-in bookings (no user account). NULL for online bookings (use profiles.name instead).';
COMMENT ON COLUMN bookings.customer_phone IS 'Customer phone for walk-in bookings (no user account). NULL for online bookings (use profiles.phone instead).';
