-- Migration: Add RLS policies for cafe_images table
-- Description: Allow admins and owners to delete cafe images
-- Author: Generated by Claude Code
-- Date: 2025-12-31

-- Enable RLS on cafe_images if table exists
DO $$
BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'cafe_images') THEN
    ALTER TABLE cafe_images ENABLE ROW LEVEL SECURITY;
  END IF;
END $$;

-- CAFE_IMAGES POLICIES
DO $$
BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'cafe_images') THEN
    -- DROP existing cafe_images policies
    DROP POLICY IF EXISTS "Admins can delete cafe images" ON cafe_images;
    DROP POLICY IF EXISTS "Owners can delete own cafe images" ON cafe_images;
    DROP POLICY IF EXISTS "Anyone can view cafe images" ON cafe_images;
    DROP POLICY IF EXISTS "Owners can insert own cafe images" ON cafe_images;
    DROP POLICY IF EXISTS "Owners can update own cafe images" ON cafe_images;

    -- SELECT: Anyone can view cafe images
    EXECUTE 'CREATE POLICY "Anyone can view cafe images" ON cafe_images FOR SELECT USING (true)';

    -- INSERT: Owners can insert images for their cafes, admins can insert for any cafe
    EXECUTE 'CREATE POLICY "Owners can insert own cafe images" ON cafe_images FOR INSERT WITH CHECK (
      EXISTS (
        SELECT 1 FROM cafes
        WHERE cafes.id = cafe_images.cafe_id
        AND cafes.owner_id = auth.uid()
      )
      OR
      EXISTS (
        SELECT 1 FROM profiles
        WHERE profiles.id = auth.uid()
        AND (profiles.role IN (''admin'', ''super_admin'') OR profiles.is_admin = true)
      )
    )';

    -- UPDATE: Owners can update images for their cafes, admins can update any
    EXECUTE 'CREATE POLICY "Owners can update own cafe images" ON cafe_images FOR UPDATE USING (
      EXISTS (
        SELECT 1 FROM cafes
        WHERE cafes.id = cafe_images.cafe_id
        AND cafes.owner_id = auth.uid()
      )
      OR
      EXISTS (
        SELECT 1 FROM profiles
        WHERE profiles.id = auth.uid()
        AND (profiles.role IN (''admin'', ''super_admin'') OR profiles.is_admin = true)
      )
    )';

    -- DELETE: Owners can delete images for their cafes, admins can delete any
    EXECUTE 'CREATE POLICY "Owners can delete own cafe images" ON cafe_images FOR DELETE USING (
      EXISTS (
        SELECT 1 FROM cafes
        WHERE cafes.id = cafe_images.cafe_id
        AND cafes.owner_id = auth.uid()
      )
      OR
      EXISTS (
        SELECT 1 FROM profiles
        WHERE profiles.id = auth.uid()
        AND (profiles.role IN (''admin'', ''super_admin'') OR profiles.is_admin = true)
      )
    )';

    -- Add comment
    COMMENT ON TABLE cafe_images IS 'Cafe images table with RLS enabled. Owners can manage images for their cafes, admins can manage all.';
  END IF;
END $$;
