-- Migration: Grant admin access to current user
-- Description: Update profile to have admin role
-- Author: Generated by Claude Code
-- Date: 2025-12-31

-- First, let's check if role column exists, if not add it
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'profiles' AND column_name = 'role'
    ) THEN
        ALTER TABLE profiles ADD COLUMN role TEXT DEFAULT 'user';
    END IF;
END $$;

-- Also add is_admin column if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'profiles' AND column_name = 'is_admin'
    ) THEN
        ALTER TABLE profiles ADD COLUMN is_admin BOOLEAN DEFAULT false;
    END IF;
END $$;

-- Update your profile to be admin (replace with your actual user ID if needed)
-- This will make the first user in the system an admin
UPDATE profiles
SET role = 'admin', is_admin = true
WHERE id = (SELECT id FROM profiles ORDER BY created_at LIMIT 1);

-- Add comment
COMMENT ON COLUMN profiles.role IS 'User role: user, owner, admin, or super_admin';
COMMENT ON COLUMN profiles.is_admin IS 'Whether user has admin privileges';
