-- Migration: Enable Row Level Security for bookings and booking_items
-- Description: Implement proper RLS policies to secure booking data
-- Author: Generated by Claude Code
-- Date: 2025-12-18

-- Enable RLS on bookings table
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;

-- Enable RLS on booking_items table
ALTER TABLE booking_items ENABLE ROW LEVEL SECURITY;

-- Policy 1: Users can view their own bookings
CREATE POLICY "Users can view own bookings"
ON bookings
FOR SELECT
USING (
  auth.uid() = user_id
  OR
  -- Cafe owners can view bookings for their cafes
  EXISTS (
    SELECT 1 FROM cafes
    WHERE cafes.id = bookings.cafe_id
    AND cafes.owner_id = auth.uid()
  )
  OR
  -- Admins can view all bookings
  EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid()
    AND (profiles.role IN ('admin', 'super_admin') OR profiles.is_admin = true)
  )
);

-- Policy 2: Users can insert their own bookings (authenticated users only)
CREATE POLICY "Authenticated users can create bookings"
ON bookings
FOR INSERT
WITH CHECK (
  auth.uid() IS NOT NULL
  AND auth.uid() = user_id
);

-- Policy 3: Users can update their own bookings (cancel only)
CREATE POLICY "Users can update own bookings"
ON bookings
FOR UPDATE
USING (
  auth.uid() = user_id
  OR
  -- Cafe owners can update bookings for their cafes
  EXISTS (
    SELECT 1 FROM cafes
    WHERE cafes.id = bookings.cafe_id
    AND cafes.owner_id = auth.uid()
  )
  OR
  -- Admins can update any booking
  EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid()
    AND (profiles.role IN ('admin', 'super_admin') OR profiles.is_admin = true)
  )
)
WITH CHECK (
  auth.uid() = user_id
  OR
  EXISTS (
    SELECT 1 FROM cafes
    WHERE cafes.id = bookings.cafe_id
    AND cafes.owner_id = auth.uid()
  )
  OR
  EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid()
    AND (profiles.role IN ('admin', 'super_admin') OR profiles.is_admin = true)
  )
);

-- Policy 4: Users can delete (cancel) their own bookings
CREATE POLICY "Users can delete own bookings"
ON bookings
FOR DELETE
USING (
  auth.uid() = user_id
  OR
  -- Cafe owners can delete bookings for their cafes
  EXISTS (
    SELECT 1 FROM cafes
    WHERE cafes.id = bookings.cafe_id
    AND cafes.owner_id = auth.uid()
  )
  OR
  -- Admins can delete any booking
  EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid()
    AND (profiles.role IN ('admin', 'super_admin') OR profiles.is_admin = true)
  )
);

-- BOOKING ITEMS POLICIES

-- Policy 1: Users can view booking items for their bookings
CREATE POLICY "Users can view own booking items"
ON booking_items
FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM bookings
    WHERE bookings.id = booking_items.booking_id
    AND (
      bookings.user_id = auth.uid()
      OR
      EXISTS (
        SELECT 1 FROM cafes
        WHERE cafes.id = bookings.cafe_id
        AND cafes.owner_id = auth.uid()
      )
      OR
      EXISTS (
        SELECT 1 FROM profiles
        WHERE profiles.id = auth.uid()
        AND (profiles.role IN ('admin', 'super_admin') OR profiles.is_admin = true)
      )
    )
  )
);

-- Policy 2: Users can insert booking items for their bookings
CREATE POLICY "Users can create booking items for own bookings"
ON booking_items
FOR INSERT
WITH CHECK (
  EXISTS (
    SELECT 1 FROM bookings
    WHERE bookings.id = booking_items.booking_id
    AND bookings.user_id = auth.uid()
  )
);

-- Policy 3: Users can update booking items for their bookings
CREATE POLICY "Users can update own booking items"
ON booking_items
FOR UPDATE
USING (
  EXISTS (
    SELECT 1 FROM bookings
    WHERE bookings.id = booking_items.booking_id
    AND (
      bookings.user_id = auth.uid()
      OR
      EXISTS (
        SELECT 1 FROM cafes
        WHERE cafes.id = bookings.cafe_id
        AND cafes.owner_id = auth.uid()
      )
      OR
      EXISTS (
        SELECT 1 FROM profiles
        WHERE profiles.id = auth.uid()
        AND (profiles.role IN ('admin', 'super_admin') OR profiles.is_admin = true)
      )
    )
  )
);

-- Policy 4: Users can delete booking items for their bookings
CREATE POLICY "Users can delete own booking items"
ON booking_items
FOR DELETE
USING (
  EXISTS (
    SELECT 1 FROM bookings
    WHERE bookings.id = booking_items.booking_id
    AND (
      bookings.user_id = auth.uid()
      OR
      EXISTS (
        SELECT 1 FROM cafes
        WHERE cafes.id = bookings.cafe_id
        AND cafes.owner_id = auth.uid()
      )
      OR
      EXISTS (
        SELECT 1 FROM profiles
        WHERE profiles.id = auth.uid()
        AND (profiles.role IN ('admin', 'super_admin') OR profiles.is_admin = true)
      )
    )
  )
);

-- Enable RLS on cafes table as well for consistency
ALTER TABLE cafes ENABLE ROW LEVEL SECURITY;

-- Policy: Everyone can view active cafes
CREATE POLICY "Anyone can view active cafes"
ON cafes
FOR SELECT
USING (is_active = true OR owner_id = auth.uid() OR EXISTS (
  SELECT 1 FROM profiles
  WHERE profiles.id = auth.uid()
  AND (profiles.role IN ('admin', 'super_admin') OR profiles.is_admin = true)
));

-- Policy: Owners and admins can update their own cafes
CREATE POLICY "Owners can update own cafes"
ON cafes
FOR UPDATE
USING (
  owner_id = auth.uid()
  OR
  EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid()
    AND (profiles.role IN ('admin', 'super_admin') OR profiles.is_admin = true)
  )
);

-- Policy: Admins can insert cafes
CREATE POLICY "Admins can insert cafes"
ON cafes
FOR INSERT
WITH CHECK (
  EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid()
    AND (profiles.role IN ('admin', 'super_admin') OR profiles.is_admin = true)
  )
);

-- Comment explaining the security model
COMMENT ON TABLE bookings IS 'Bookings table with RLS enabled. Users can only see their own bookings, cafe owners can see bookings for their cafes, admins can see all.';
COMMENT ON TABLE booking_items IS 'Booking items table with RLS enabled. Access controlled through parent booking relationship.';
