-- Migration: Add DELETE policy for admins on cafes table
-- Description: Allow admins to delete cafes through RLS policy
-- Author: Generated by Claude Code
-- Date: 2025-12-31

-- Add DELETE policy for admins on cafes table
CREATE POLICY "Admins can delete cafes"
ON cafes
FOR DELETE
USING (
  EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid()
    AND (profiles.role IN ('admin', 'super_admin') OR profiles.is_admin = true)
  )
);

-- Add comment
COMMENT ON POLICY "Admins can delete cafes" ON cafes IS 'Allows administrators to delete cafes and all related data';
