-- Migration: Create gallery_images table
-- Description: Create table to store cafe gallery images
-- Author: Generated by Claude Code
-- Date: 2025-12-31

-- Create gallery_images table if it doesn't exist
CREATE TABLE IF NOT EXISTS gallery_images (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cafe_id UUID NOT NULL REFERENCES cafes(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE gallery_images ENABLE ROW LEVEL SECURITY;

-- Create index on cafe_id for faster queries
CREATE INDEX IF NOT EXISTS idx_gallery_images_cafe_id ON gallery_images(cafe_id);
CREATE INDEX IF NOT EXISTS idx_gallery_images_created_at ON gallery_images(created_at DESC);

-- Allow anyone to read gallery images
CREATE POLICY "Allow public read access to gallery images"
ON gallery_images
FOR SELECT
USING (true);

-- Allow anyone to insert gallery images (owner dashboard will use this)
CREATE POLICY "Allow insert for all users"
ON gallery_images
FOR INSERT
WITH CHECK (true);

-- Allow anyone to delete gallery images (owner dashboard will use this)
CREATE POLICY "Allow delete for all users"
ON gallery_images
FOR DELETE
USING (true);

-- Add comments
COMMENT ON TABLE gallery_images IS 'Stores gallery images for cafes';
COMMENT ON COLUMN gallery_images.id IS 'Unique identifier for gallery image';
COMMENT ON COLUMN gallery_images.cafe_id IS 'Reference to cafe that owns this image';
COMMENT ON COLUMN gallery_images.image_url IS 'Public URL of the image';
COMMENT ON COLUMN gallery_images.created_at IS 'Timestamp when image was uploaded';
COMMENT ON COLUMN gallery_images.updated_at IS 'Timestamp when image was last updated';
