-- Migration: Fix admin login function - remove email column
-- Description: Remove email from function since profiles table doesn't have it
-- Author: Generated by Claude Code
-- Date: 2025-12-31

-- Drop function if exists
DROP FUNCTION IF EXISTS public.verify_admin_login(TEXT, TEXT);

-- Create a function to verify admin login credentials (without email)
CREATE FUNCTION public.verify_admin_login(
  p_username TEXT,
  p_password TEXT
)
RETURNS TABLE (
  user_id UUID,
  username TEXT,
  is_valid BOOLEAN
)
SECURITY DEFINER
SET search_path = public
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    p.id as user_id,
    p.admin_username as username,
    (
      COALESCE(p.admin_password, 'admin123') = p_password AND
      (p.is_admin = true OR p.role IN ('admin', 'super_admin'))
    ) as is_valid
  FROM public.profiles p
  WHERE p.admin_username = p_username
  LIMIT 1;
END;
$$;

-- Grant execute permission to anonymous and authenticated users
GRANT EXECUTE ON FUNCTION public.verify_admin_login(TEXT, TEXT) TO anon;
GRANT EXECUTE ON FUNCTION public.verify_admin_login(TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.verify_admin_login(TEXT, TEXT) TO service_role;

-- Add comment
COMMENT ON FUNCTION public.verify_admin_login IS 'Securely verify admin login credentials without exposing password in response';
