-- Migration: Add payment_mode to bookings
-- Description: Add payment_mode column to track how customers paid (cash, upi)
-- Author: Generated by Claude Code
-- Date: 2025-12-29

-- Add payment_mode column
ALTER TABLE bookings
ADD COLUMN IF NOT EXISTS payment_mode TEXT DEFAULT 'cash';

-- Add comment explaining the column
COMMENT ON COLUMN bookings.payment_mode IS 'Payment method used for the booking. Values: cash, upi. Defaults to cash for legacy bookings.';
