-- Migration: Add slug column to cafes table for SEO-friendly URLs
-- Description: Add slug column and generate slugs from cafe names
-- Author: Generated by Claude Code
-- Date: 2025-12-19

-- Add slug column to cafes table
ALTER TABLE cafes
ADD COLUMN IF NOT EXISTS slug TEXT;

-- Create a function to generate slug from name
CREATE OR REPLACE FUNCTION generate_slug(name TEXT) RETURNS TEXT AS $$
DECLARE
  slug TEXT;
BEGIN
  -- Convert to lowercase, replace spaces with hyphens, remove special characters
  slug := LOWER(name);
  slug := REGEXP_REPLACE(slug, '[^a-z0-9\s-]', '', 'g');
  slug := REGEXP_REPLACE(slug, '\s+', '-', 'g');
  slug := REGEXP_REPLACE(slug, '-+', '-', 'g');
  slug := TRIM(BOTH '-' FROM slug);
  RETURN slug;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- Generate slugs for existing cafes
UPDATE cafes
SET slug = generate_slug(name)
WHERE slug IS NULL AND name IS NOT NULL;

-- Add unique constraint on slug
ALTER TABLE cafes
ADD CONSTRAINT cafes_slug_unique UNIQUE (slug);

-- Add index for faster slug lookups
CREATE INDEX IF NOT EXISTS cafes_slug_idx ON cafes(slug);

-- Create a trigger to auto-generate slug on insert/update
CREATE OR REPLACE FUNCTION auto_generate_slug() RETURNS TRIGGER AS $$
BEGIN
  -- Only generate slug if it's not provided or name changed
  IF NEW.slug IS NULL OR (TG_OP = 'UPDATE' AND NEW.name != OLD.name) THEN
    NEW.slug := generate_slug(NEW.name);

    -- Handle duplicate slugs by appending a number
    DECLARE
      base_slug TEXT := NEW.slug;
      counter INT := 1;
    BEGIN
      WHILE EXISTS (SELECT 1 FROM cafes WHERE slug = NEW.slug AND id != NEW.id) LOOP
        NEW.slug := base_slug || '-' || counter;
        counter := counter + 1;
      END LOOP;
    END;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger
DROP TRIGGER IF EXISTS cafes_auto_slug ON cafes;
CREATE TRIGGER cafes_auto_slug
  BEFORE INSERT OR UPDATE ON cafes
  FOR EACH ROW
  EXECUTE FUNCTION auto_generate_slug();

-- Add comment
COMMENT ON COLUMN cafes.slug IS 'SEO-friendly URL slug generated from cafe name. Used in URLs like /cafes/game-zone-cafe instead of UUID.';
