-- Migration: Add RLS policies for console_pricing and gallery_images tables
-- Description: Allow admins and owners to delete related records
-- Author: Generated by Claude Code
-- Date: 2025-12-31

-- Enable RLS on console_pricing if not already enabled
ALTER TABLE console_pricing ENABLE ROW LEVEL SECURITY;

-- Enable RLS on cafe_images if table exists
DO $$
BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'cafe_images') THEN
    ALTER TABLE cafe_images ENABLE ROW LEVEL SECURITY;
  END IF;
END $$;

-- DROP existing policies if they exist to avoid conflicts
DROP POLICY IF EXISTS "Admins can delete console pricing" ON console_pricing;
DROP POLICY IF EXISTS "Owners can delete own cafe pricing" ON console_pricing;
DROP POLICY IF EXISTS "Anyone can view console pricing" ON console_pricing;
DROP POLICY IF EXISTS "Admins can insert console pricing" ON console_pricing;
DROP POLICY IF EXISTS "Owners can insert own cafe pricing" ON console_pricing;
DROP POLICY IF EXISTS "Owners can update own cafe pricing" ON console_pricing;

-- CONSOLE_PRICING POLICIES

-- SELECT: Anyone can view console pricing
CREATE POLICY "Anyone can view console pricing"
ON console_pricing
FOR SELECT
USING (true);

-- INSERT: Owners can insert pricing for their cafes, admins can insert for any cafe
CREATE POLICY "Owners can insert own cafe pricing"
ON console_pricing
FOR INSERT
WITH CHECK (
  EXISTS (
    SELECT 1 FROM cafes
    WHERE cafes.id = console_pricing.cafe_id
    AND cafes.owner_id = auth.uid()
  )
  OR
  EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid()
    AND (profiles.role IN ('admin', 'super_admin') OR profiles.is_admin = true)
  )
);

-- UPDATE: Owners can update pricing for their cafes, admins can update any
CREATE POLICY "Owners can update own cafe pricing"
ON console_pricing
FOR UPDATE
USING (
  EXISTS (
    SELECT 1 FROM cafes
    WHERE cafes.id = console_pricing.cafe_id
    AND cafes.owner_id = auth.uid()
  )
  OR
  EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid()
    AND (profiles.role IN ('admin', 'super_admin') OR profiles.is_admin = true)
  )
);

-- DELETE: Owners can delete pricing for their cafes, admins can delete any
CREATE POLICY "Owners can delete own cafe pricing"
ON console_pricing
FOR DELETE
USING (
  EXISTS (
    SELECT 1 FROM cafes
    WHERE cafes.id = console_pricing.cafe_id
    AND cafes.owner_id = auth.uid()
  )
  OR
  EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid()
    AND (profiles.role IN ('admin', 'super_admin') OR profiles.is_admin = true)
  )
);

-- CAFE_IMAGES POLICIES (only if table exists)

DO $$
BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'cafe_images') THEN
    -- DROP existing cafe_images policies
    DROP POLICY IF EXISTS "Admins can delete cafe images" ON cafe_images;
    DROP POLICY IF EXISTS "Owners can delete own cafe images" ON cafe_images;
    DROP POLICY IF EXISTS "Anyone can view cafe images" ON cafe_images;
    DROP POLICY IF EXISTS "Owners can insert own cafe images" ON cafe_images;
    DROP POLICY IF EXISTS "Owners can update own cafe images" ON cafe_images;

    -- SELECT: Anyone can view cafe images
    EXECUTE 'CREATE POLICY "Anyone can view cafe images" ON cafe_images FOR SELECT USING (true)';

    -- INSERT: Owners can insert images for their cafes, admins can insert for any cafe
    EXECUTE 'CREATE POLICY "Owners can insert own cafe images" ON cafe_images FOR INSERT WITH CHECK (
      EXISTS (
        SELECT 1 FROM cafes
        WHERE cafes.id = cafe_images.cafe_id
        AND cafes.owner_id = auth.uid()
      )
      OR
      EXISTS (
        SELECT 1 FROM profiles
        WHERE profiles.id = auth.uid()
        AND (profiles.role IN (''admin'', ''super_admin'') OR profiles.is_admin = true)
      )
    )';

    -- UPDATE: Owners can update images for their cafes, admins can update any
    EXECUTE 'CREATE POLICY "Owners can update own cafe images" ON cafe_images FOR UPDATE USING (
      EXISTS (
        SELECT 1 FROM cafes
        WHERE cafes.id = cafe_images.cafe_id
        AND cafes.owner_id = auth.uid()
      )
      OR
      EXISTS (
        SELECT 1 FROM profiles
        WHERE profiles.id = auth.uid()
        AND (profiles.role IN (''admin'', ''super_admin'') OR profiles.is_admin = true)
      )
    )';

    -- DELETE: Owners can delete images for their cafes, admins can delete any
    EXECUTE 'CREATE POLICY "Owners can delete own cafe images" ON cafe_images FOR DELETE USING (
      EXISTS (
        SELECT 1 FROM cafes
        WHERE cafes.id = cafe_images.cafe_id
        AND cafes.owner_id = auth.uid()
      )
      OR
      EXISTS (
        SELECT 1 FROM profiles
        WHERE profiles.id = auth.uid()
        AND (profiles.role IN (''admin'', ''super_admin'') OR profiles.is_admin = true)
      )
    )';

    -- Add comment
    COMMENT ON TABLE cafe_images IS 'Cafe images table with RLS enabled. Owners can manage images for their cafes, admins can manage all.';
  END IF;
END $$;

-- Add comment for console_pricing
COMMENT ON TABLE console_pricing IS 'Console pricing table with RLS enabled. Owners can manage pricing for their cafes, admins can manage all.';
