-- Migration: Add admin credentials columns
-- Description: Add admin_username and admin_password columns to profiles table for admin login
-- Author: Generated by Claude Code
-- Date: 2025-12-31

-- Add admin_username column
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'profiles' AND column_name = 'admin_username'
    ) THEN
        ALTER TABLE profiles ADD COLUMN admin_username TEXT;
    END IF;
END $$;

-- Add admin_password column (NOTE: In production, use proper password hashing!)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'profiles' AND column_name = 'admin_password'
    ) THEN
        ALTER TABLE profiles ADD COLUMN admin_password TEXT;
    END IF;
END $$;

-- Set default admin credentials for existing admin users
UPDATE profiles
SET
    admin_username = 'admin',
    admin_password = 'admin123'
WHERE
    (role IN ('admin', 'super_admin') OR is_admin = true)
    AND admin_username IS NULL;

-- Add comments
COMMENT ON COLUMN profiles.admin_username IS 'Admin panel login username (only for admin users)';
COMMENT ON COLUMN profiles.admin_password IS 'Admin panel login password - NOTE: Should use proper hashing in production';
