-- Migration: Ensure an owner user exists in profiles table
-- Description: Create or update an owner user with credentials for owner portal access
-- Author: Generated by Claude Code
-- Date: 2025-12-31

-- Check if there's already an owner user, if not create one
DO $$
DECLARE
  owner_count INTEGER;
  new_user_id UUID;
BEGIN
  -- Count existing owner users
  SELECT COUNT(*) INTO owner_count
  FROM profiles
  WHERE role = 'owner';

  -- If no owner exists, create one
  IF owner_count = 0 THEN
    -- Generate a new UUID for the owner user
    new_user_id := gen_random_uuid();

    -- Insert the owner profile
    INSERT INTO profiles (
      id,
      first_name,
      last_name,
      phone,
      role,
      owner_username,
      owner_password,
      created_at,
      updated_at
    ) VALUES (
      new_user_id,
      'Cafe',
      'Owner',
      NULL,
      'owner',
      'owner',
      'owner123',
      NOW(),
      NOW()
    );

    RAISE NOTICE 'Created new owner user with username: owner, password: owner123';
  ELSE
    -- Owner exists, just make sure credentials are set
    UPDATE profiles
    SET
      owner_username = COALESCE(owner_username, 'owner'),
      owner_password = COALESCE(owner_password, 'owner123'),
      updated_at = NOW()
    WHERE role = 'owner'
      AND (owner_username IS NULL OR owner_password IS NULL);

    RAISE NOTICE 'Updated existing owner user credentials';
  END IF;
END $$;
