-- Migration: Add owner login verification function
-- Description: Create a secure function to verify owner credentials without exposing passwords
-- Author: Generated by Claude Code
-- Date: 2025-12-31

-- Drop function if exists
DROP FUNCTION IF EXISTS public.verify_owner_login(TEXT, TEXT);

-- Create a function to verify owner login credentials (without email)
CREATE FUNCTION public.verify_owner_login(
  p_username TEXT,
  p_password TEXT
)
RETURNS TABLE (
  user_id UUID,
  username TEXT,
  is_valid BOOLEAN
)
SECURITY DEFINER
SET search_path = public
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    p.id as user_id,
    p.owner_username as username,
    (
      COALESCE(p.owner_password, 'owner123') = p_password AND
      p.role = 'owner'
    ) as is_valid
  FROM public.profiles p
  WHERE p.owner_username = p_username
  LIMIT 1;
END;
$$;

-- Grant execute permission to anonymous and authenticated users
GRANT EXECUTE ON FUNCTION public.verify_owner_login(TEXT, TEXT) TO anon;
GRANT EXECUTE ON FUNCTION public.verify_owner_login(TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.verify_owner_login(TEXT, TEXT) TO service_role;

-- Add comment
COMMENT ON FUNCTION public.verify_owner_login IS 'Securely verify owner login credentials without exposing password in response';
