-- Migration: Create audit_logs table for tracking admin actions
-- Description: Track all admin actions for security and compliance
-- Author: Generated by Claude Code
-- Date: 2025-12-31

-- Create audit_logs table
CREATE TABLE IF NOT EXISTS audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT,
  details JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_audit_logs_admin_id ON audit_logs(admin_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action);

-- Enable RLS
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- Policy: Only admins can view audit logs
CREATE POLICY "Admins can view audit logs"
ON audit_logs
FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid()
    AND (profiles.role IN ('admin', 'super_admin') OR profiles.is_admin = true)
  )
);

-- Policy: Only the system can insert audit logs (via service role)
CREATE POLICY "System can insert audit logs"
ON audit_logs
FOR INSERT
WITH CHECK (true);

-- Add comments
COMMENT ON TABLE audit_logs IS 'Audit log table tracking all admin actions for security and compliance';
COMMENT ON COLUMN audit_logs.admin_id IS 'ID of the admin who performed the action';
COMMENT ON COLUMN audit_logs.action IS 'Type of action (e.g., create, update, delete, activate, deactivate)';
COMMENT ON COLUMN audit_logs.entity_type IS 'Type of entity affected (e.g., cafe, user, booking)';
COMMENT ON COLUMN audit_logs.entity_id IS 'ID of the affected entity';
COMMENT ON COLUMN audit_logs.details IS 'Additional details about the action in JSON format';
