-- Migration: Add price_starts_from field to cafes table
-- Description: Add field to store the starting price for the café
-- Author: Generated by Claude Code
-- Date: 2025-12-30

-- Add price_starts_from column
ALTER TABLE cafes
ADD COLUMN IF NOT EXISTS price_starts_from INTEGER;

-- Add comment
COMMENT ON COLUMN cafes.price_starts_from IS 'Starting price for services (e.g., ₹50)';
