-- Migration: Add admin login verification function
-- Description: Create a secure function to verify admin credentials without exposing passwords
-- Author: Generated by Claude Code
-- Date: 2025-12-31

-- Drop function if exists
DROP FUNCTION IF EXISTS verify_admin_login(TEXT, TEXT);

-- Create a function to verify admin login credentials
CREATE OR REPLACE FUNCTION public.verify_admin_login(
  p_username TEXT,
  p_password TEXT
)
RETURNS TABLE (
  user_id UUID,
  username TEXT,
  email TEXT,
  is_valid BOOLEAN
)
SECURITY DEFINER
SET search_path = public
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    p.id as user_id,
    p.admin_username as username,
    p.email,
    (
      p.admin_password = p_password AND
      (p.is_admin = true OR p.role IN ('admin', 'super_admin'))
    ) as is_valid
  FROM public.profiles p
  WHERE p.admin_username = p_username
  LIMIT 1;
END;
$$;

-- Grant execute permission to anonymous and authenticated users
GRANT EXECUTE ON FUNCTION public.verify_admin_login(TEXT, TEXT) TO anon, authenticated;

-- Add comment
COMMENT ON FUNCTION public.verify_admin_login IS 'Securely verify admin login credentials without exposing password in response';
