-- Migration: Remove walk-in booking fields
-- Description: Remove customer_name and customer_phone columns from bookings table as walk-in functionality is being removed
-- Author: Generated by Claude Code
-- Date: 2025-12-18

-- Remove customer info columns that were added for walk-in bookings
ALTER TABLE bookings
DROP COLUMN IF EXISTS customer_name,
DROP COLUMN IF EXISTS customer_phone;

-- Note: The source column is kept as it may be useful for historical data and analytics
-- Even though new bookings will only be "online", existing data may have "walk_in" values
