-- Migration: Ensure owner_id column exists in cafes table
-- Description: Add owner_id column if it doesn't exist
-- Author: Generated by Claude Code
-- Date: 2025-12-31

-- Add owner_id column if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'cafes' AND column_name = 'owner_id'
    ) THEN
        ALTER TABLE cafes ADD COLUMN owner_id UUID REFERENCES auth.users(id);

        -- Set owner_id from user_id if user_id exists
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'cafes' AND column_name = 'user_id'
        ) THEN
            UPDATE cafes SET owner_id = user_id WHERE owner_id IS NULL;
        END IF;
    END IF;
END $$;

-- Add comment
COMMENT ON COLUMN cafes.owner_id IS 'ID of the user who owns this café';
