-- Migration: Add contact and hours fields to cafes table
-- Description: Add phone, email, and opening_hours columns for café settings
-- Author: Generated by Claude Code
-- Date: 2025-12-30

-- Add phone column
ALTER TABLE cafes
ADD COLUMN IF NOT EXISTS phone TEXT;

-- Add email column
ALTER TABLE cafes
ADD COLUMN IF NOT EXISTS email TEXT;

-- Add opening_hours column (already exists in some cafes, make sure it's there)
ALTER TABLE cafes
ADD COLUMN IF NOT EXISTS opening_hours TEXT;

-- Add comments
COMMENT ON COLUMN cafes.phone IS 'Contact phone number for the café';
COMMENT ON COLUMN cafes.email IS 'Contact email address for the café';
COMMENT ON COLUMN cafes.opening_hours IS 'Operating hours (e.g., "Mon-Sun: 09:00 AM - 11:00 PM")';
