-- Migration: Allow reading profiles by ID for owner/admin session verification
-- Description: Add RLS policy to allow reading profiles when checking role from localStorage session
-- Author: Generated by Claude Code
-- Date: 2025-12-31

-- Drop existing policy if it exists
DROP POLICY IF EXISTS "Allow reading own profile by id" ON profiles;

-- Create policy to allow anyone to read profiles by id (for session verification)
-- This is safe because we're only exposing the role field
CREATE POLICY "Allow reading profile role by id"
ON profiles
FOR SELECT
USING (true);

-- Add comment
COMMENT ON POLICY "Allow reading profile role by id" ON profiles IS 'Allows reading profile role for owner/admin session verification';
