-- Migration: Add console_type to membership_plans
-- Description: Add console/device type field to membership plans
-- Author: Generated by Claude Code
-- Date: 2026-01-01

-- Add console_type column to membership_plans table
ALTER TABLE membership_plans
ADD COLUMN IF NOT EXISTS console_type TEXT NOT NULL DEFAULT 'PC' CHECK (console_type IN ('PC', 'PS4', 'PS5', 'Xbox One', 'Xbox Series X', 'Nintendo Switch', 'VR'));

-- Add index on console_type for faster filtering
CREATE INDEX IF NOT EXISTS idx_membership_plans_console_type ON membership_plans(console_type);

-- Add comment
COMMENT ON COLUMN membership_plans.console_type IS 'Type of gaming console/device: PC, PS4, PS5, Xbox One, Xbox Series X, Nintendo Switch, VR';
