-- Migration: Add player_count to membership_plans
-- Description: Add player count field (single/double player) to membership plans
-- Author: Generated by Claude Code
-- Date: 2026-01-01

-- Add player_count column to membership_plans table
ALTER TABLE membership_plans
ADD COLUMN IF NOT EXISTS player_count TEXT NOT NULL DEFAULT 'single' CHECK (player_count IN ('single', 'double'));

-- Add index on player_count for faster filtering
CREATE INDEX IF NOT EXISTS idx_membership_plans_player_count ON membership_plans(player_count);

-- Add comment
COMMENT ON COLUMN membership_plans.player_count IS 'Number of players: single or double';
