-- Migration: Create cafe_consoles table
-- Description: Store which consoles are available at each cafe
-- Author: Generated by Claude Code
-- Date: 2026-01-01

-- Create cafe_consoles table
CREATE TABLE IF NOT EXISTS cafe_consoles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cafe_id UUID NOT NULL REFERENCES cafes(id) ON DELETE CASCADE,
  console_type TEXT NOT NULL CHECK (console_type IN ('PC', 'PS4', 'PS5', 'Xbox One', 'Xbox Series X', 'Nintendo Switch', 'VR')),
  quantity INTEGER NOT NULL DEFAULT 1,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(cafe_id, console_type)
);

-- Enable RLS
ALTER TABLE cafe_consoles ENABLE ROW LEVEL SECURITY;

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_cafe_consoles_cafe_id ON cafe_consoles(cafe_id);
CREATE INDEX IF NOT EXISTS idx_cafe_consoles_is_active ON cafe_consoles(is_active);

-- Allow anyone to read active cafe consoles
CREATE POLICY "Allow public read access to active cafe consoles"
ON cafe_consoles
FOR SELECT
USING (is_active = true);

-- Allow cafe owners to manage their consoles
CREATE POLICY "Allow owners to manage their cafe consoles"
ON cafe_consoles
FOR ALL
USING (true)
WITH CHECK (true);

-- Add comments
COMMENT ON TABLE cafe_consoles IS 'Stores which gaming consoles are available at each cafe';
COMMENT ON COLUMN cafe_consoles.id IS 'Unique identifier for the console entry';
COMMENT ON COLUMN cafe_consoles.cafe_id IS 'Reference to the cafe';
COMMENT ON COLUMN cafe_consoles.console_type IS 'Type of console: PC, PS4, PS5, Xbox One, Xbox Series X, Nintendo Switch, VR';
COMMENT ON COLUMN cafe_consoles.quantity IS 'Number of units available';
COMMENT ON COLUMN cafe_consoles.is_active IS 'Whether this console is currently available';
