-- Migration: Add more console types to cafes
-- Description: Add Xbox, Nintendo Switch, and VR consoles
-- Author: Generated by Claude Code
-- Date: 2026-01-01

-- Add Xbox Series X
INSERT INTO cafe_consoles (cafe_id, console_type, quantity, is_active)
SELECT
  id as cafe_id,
  'Xbox Series X' as console_type,
  2 as quantity,
  true as is_active
FROM cafes
ON CONFLICT (cafe_id, console_type) DO NOTHING;

-- Add Xbox One
INSERT INTO cafe_consoles (cafe_id, console_type, quantity, is_active)
SELECT
  id as cafe_id,
  'Xbox One' as console_type,
  2 as quantity,
  true as is_active
FROM cafes
ON CONFLICT (cafe_id, console_type) DO NOTHING;

-- Add Nintendo Switch
INSERT INTO cafe_consoles (cafe_id, console_type, quantity, is_active)
SELECT
  id as cafe_id,
  'Nintendo Switch' as console_type,
  2 as quantity,
  true as is_active
FROM cafes
ON CONFLICT (cafe_id, console_type) DO NOTHING;

-- Add VR
INSERT INTO cafe_consoles (cafe_id, console_type, quantity, is_active)
SELECT
  id as cafe_id,
  'VR' as console_type,
  1 as quantity,
  true as is_active
FROM cafes
ON CONFLICT (cafe_id, console_type) DO NOTHING;

-- Add comment
COMMENT ON TABLE cafe_consoles IS 'All console types (PC, PS4, PS5, Xbox One, Xbox Series X, Nintendo Switch, VR) have been added to all cafes.';
