-- Migration: Add default consoles to cafes
-- Description: Add common gaming consoles to existing cafes
-- Author: Generated by Claude Code
-- Date: 2026-01-01

-- Add consoles for all existing cafes
-- This will add PC, PS5, and PS4 by default to each cafe
INSERT INTO cafe_consoles (cafe_id, console_type, quantity, is_active)
SELECT
  id as cafe_id,
  'PC' as console_type,
  10 as quantity,
  true as is_active
FROM cafes
ON CONFLICT (cafe_id, console_type) DO NOTHING;

INSERT INTO cafe_consoles (cafe_id, console_type, quantity, is_active)
SELECT
  id as cafe_id,
  'PS5' as console_type,
  5 as quantity,
  true as is_active
FROM cafes
ON CONFLICT (cafe_id, console_type) DO NOTHING;

INSERT INTO cafe_consoles (cafe_id, console_type, quantity, is_active)
SELECT
  id as cafe_id,
  'PS4' as console_type,
  3 as quantity,
  true as is_active
FROM cafes
ON CONFLICT (cafe_id, console_type) DO NOTHING;

-- Add comment
COMMENT ON TABLE cafe_consoles IS 'Default consoles (PC, PS5, PS4) have been added to all cafes. You can modify these in the Settings tab.';
