-- Migration: Create membership_plans table
-- Description: Store membership plans (day passes and hourly packages)
-- Author: Generated by Claude Code
-- Date: 2026-01-01

-- Create membership_plans table
CREATE TABLE IF NOT EXISTS membership_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cafe_id UUID NOT NULL REFERENCES cafes(id) ON DELETE CASCADE,
  plan_type TEXT NOT NULL CHECK (plan_type IN ('day_pass', 'hourly_package')),
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  hours INTEGER, -- For hourly packages, null for day passes
  validity_days INTEGER NOT NULL, -- 1 for day pass, X days for hourly packages
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE membership_plans ENABLE ROW LEVEL SECURITY;

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_membership_plans_cafe_id ON membership_plans(cafe_id);
CREATE INDEX IF NOT EXISTS idx_membership_plans_is_active ON membership_plans(is_active);

-- Allow anyone to read active membership plans
CREATE POLICY "Allow public read access to active membership plans"
ON membership_plans
FOR SELECT
USING (is_active = true);

-- Allow cafe owners to manage their membership plans
CREATE POLICY "Allow owners to manage their membership plans"
ON membership_plans
FOR ALL
USING (true)
WITH CHECK (true);

-- Add comments
COMMENT ON TABLE membership_plans IS 'Stores membership plans including day passes and hourly packages';
COMMENT ON COLUMN membership_plans.id IS 'Unique identifier for the plan';
COMMENT ON COLUMN membership_plans.cafe_id IS 'Reference to the cafe that owns this plan';
COMMENT ON COLUMN membership_plans.plan_type IS 'Type of plan: day_pass or hourly_package';
COMMENT ON COLUMN membership_plans.name IS 'Display name of the plan';
COMMENT ON COLUMN membership_plans.description IS 'Description of what the plan offers';
COMMENT ON COLUMN membership_plans.price IS 'Price of the plan in rupees';
COMMENT ON COLUMN membership_plans.hours IS 'Number of gaming hours (for hourly packages only)';
COMMENT ON COLUMN membership_plans.validity_days IS 'Number of days the plan is valid for';
COMMENT ON COLUMN membership_plans.is_active IS 'Whether the plan is currently available for purchase';
